client_id     = os.environ['BOT_CLIENT_ID']
client_secret = os.environ['BOT_CLIENT_SECRET']
user_agent    = os.environ['BOT_USER_AGENT']
username      = os.environ['BOT_USERNAME']
password      = os.environ['BOT_PASSWORD']
subreddit     = os.environ['BOT_SUBREDDIT']
